/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error": "#ba1a1a",
        "outline-variant": "#c2c8c0",
        "surface-container-high": "#e9e8e4",
        "tertiary": "#3e2a11",
        "secondary": "#556257",
        "on-surface": "#1b1c1a",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#bccabd",
        "on-error": "#ffffff",
        "on-surface-variant": "#424843",
        "on-error-container": "#93000a",
        "secondary-fixed": "#d8e6d8",
        "tertiary-fixed": "#ffddb8",
        "on-secondary-fixed-variant": "#3d4a40",
        "inverse-on-surface": "#f2f1ed",
        "surface-dim": "#dbdad6",
        "primary-fixed-dim": "#adcfb4",
        "surface-container": "#efeeea",
        "on-primary-container": "#99baa1",
        "error-container": "#ffdad6",
        "surface": "#faf9f5",
        "outline": "#727972",
        "surface-bright": "#faf9f5",
        "tertiary-container": "#574025",
        "primary-fixed": "#c8ebd0",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#131e16",
        "on-background": "#1b1c1a",
        "secondary-container": "#d5e3d5",
        "primary-container": "#2d4b37",
        "surface-container-low": "#f4f4f0",
        "background": "#faf9f5",
        "surface-tint": "#466550",
        "on-tertiary-container": "#ccac8a",
        "on-primary-fixed-variant": "#2f4d39",
        "inverse-primary": "#adcfb4",
        "primary": "#163422",
        "inverse-surface": "#2f312e",
        "surface-variant": "#e3e2df",
        "on-tertiary-fixed": "#291802",
        "on-secondary-container": "#59665b",
        "on-primary-fixed": "#022110",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#594227",
        "surface-container-highest": "#e3e2df",
        "tertiary-fixed-dim": "#e2c19d"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "stack-md": "24px",
        "margin-mobile": "20px",
        "container-max": "1280px",
        "unit": "8px",
        "stack-sm": "12px",
        "stack-lg": "48px",
        "margin-desktop": "64px"
      },
      fontFamily: {
        "headline-lg": ["Manrope", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Manrope", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        "display-lg": ["Manrope", "sans-serif"],
        "mono": ["ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "Liberation Mono", "Courier New", "monospace"],
        "serif": ["ui-serif", "Georgia", "Cambria", "Times New Roman", "Times", "serif"],
      },
      fontSize: {
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "500"}],
        "display-lg": ["56px", {"lineHeight": "64px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "500"}],
        "headline-lg-mobile": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
      }
    },
  },
  plugins: [
    require('@tailwindcss/container-queries')
  ],
}
